# Generated by Django 4.2.3 on 2023-08-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantAuthent', '0003_lesson_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=250)),
                ('annEntre', models.CharField(max_length=250)),
            ],
        ),
    ]
