# Generated by Django 4.2.3 on 2023-08-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantAuthent', '0005_modul_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminis',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='adminis', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=100)),
                ('annEmploi', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_adminis',
            field=models.BooleanField(default=False),
        ),
    ]
